### ISSUE TITLE
Prevent simultaneous submission of multiple forms

### ISSUE THREAD

**Issue by mikekoro** [NewOldMax/react-material-ui-form-validator#135]
How can I prevent simultaneous submission of two forms? In my particular case I have login + reset password forms (in a modal window) and when you submit the reset password form it simultaneously triggers the login form.

**Comment by hemanthvrm** [comment]
Are you using two buttons is same form tag?

**Comment by mikekoro** [comment]
> Are you using two buttons in same form tag?

No they are in separate form tags...

**Comment by diegohmac** [comment]
I'm having the same issue

**Comment by dipakparmar** [comment]
@mikekoro I had the same issue, It's because of the handle change function. 

 If you noticed how the state change is handled here

```
handleChange = (event) => {
    event.persist();
    this.setState({ [event.target.name]: event.target.value });
  };
```

where it updating state which has a name with the value of your TextValidator Component.

So if you are using the same name by mistake it will update state to the same, simultaneously.

Hope this helps 👍

**Comment by NewOldMax** [comment]
@mikekoro Hi
please reproduce your issue here: https://codesandbox.io/s/new

**Comment by RussellSanders1** [comment]
If you haven't found a solution by now, I had a similar setup, and this solved the auto-submission of multiple forms
#157 

specifically `event.stopPropagation();`
