### ISSUE TITLE
Version 2.1.1 contains a breaking change

### ISSUE THREAD

**Issue by BeatrizFerreira** [NewOldMax/react-material-ui-form-validator#149]
Hello!
The company I work for uses the `react-material-ui-form-validator` as a dependency for many applications. During the last few days we've been doing many searches about an error we're getting and after that, we found out we use the `react-material-ui-form-validator` on version `2.0.1`. We declare on our `package.json` the version with the "caret" (`^`) in order to get the latest compatible version (from version `2.0.1` to < `3.0.0`)
However, the new version `2.1.1` is not compatible with `2.0.1`... (:sadpepe:)
I believe this is due to the change of the `render` method.

**Comment by NewOldMax** [comment]
@BeatrizFerreira hi
_public_ API of this library was _not changed_ because there is no breaking changes (eg you can use TextValidator and SelectValidator without any changes)
_private_ API was changed in order to use new version of "react-form-validator-core" (eg if you create your own validated components using private API (ValidatorComponent which is come from "react-form-validator-core") you must migrate them to new version manually)

So since _public_ contracts was not changed there is no needs to update major version

**Comment by RudmanMario** [comment]
@NewOldMax Just for a discussion, wouldn't it be useful to provide some sort of a warning that users of this dependency should also keep track for breaking changes of it's dependencies (if you are not dong major release for those situations)? In large projects it's almost impossible to keep track of all dependencies from projects dependencies (it can even go few more layers down).

**Comment by NewOldMax** [comment]
@RudmanMario where you want to see such warning?

**Comment by RudmanMario** [comment]
@NewOldMax On the main page possibly?

**Comment by NewOldMax** [comment]
@RudmanMario done

**Comment by RudmanMario** [comment]
@NewOldMax that was fast, nice. Thank you!
