### ISSUE TITLE
Plans to support material-ui 1.0?

### ISSUE THREAD

**Issue by davidnorth** [NewOldMax/react-material-ui-form-validator#26]
I noticed that this appears not to be compatible with the 1.0 beta of material-ui - its looking for components not included in that version

    ERROR in ../~/react-material-ui-form-validator/lib/AutoCompleteValidator.js
    Module not found: Error: Can't resolve 'material-ui/AutoComplete' in '/Users/davidnorth/src/material/node_modules/react-material-ui-form-validator/lib'

Has any work been done on this? If not I'll probably work on it myself in a fork.

**Comment by NewOldMax** [comment]
Hi,

Currently i'm not tried to use material-ui 1.0 since it's beta (it doesn't have all components I need) and some APIs and components may be changed in future.
I'm planning to add 1.x branch support when it will be ready, but not now.

If you want it now, you can add support for it and I'll create an 'beta' release

**Comment by davidnorth** [comment]
No problem, thanks for the reply. I've started work on a fork.
